"""
MedSci Skills Demo 1: Wisconsin Breast Cancer Dataset
Step 3 — Generate Presentation Slides (present-paper skill)

Creates a 12-slide academic presentation from the manuscript draft.
Includes speaker notes for each slide.

Usage: python 03_create_pptx.py
Output: output/presentation.pptx
"""

from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE
import os

# === DESIGN CONSTANTS ===
NAVY = RGBColor(0x1B, 0x2A, 0x4A)
TEAL = RGBColor(0x00, 0x72, 0xB2)
ORANGE = RGBColor(0xD5, 0x5E, 0x00)
GREEN = RGBColor(0x00, 0x9E, 0x73)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
LIGHT_GRAY = RGBColor(0xF5, 0xF5, 0xF5)
DARK_GRAY = RGBColor(0x33, 0x33, 0x33)
MED_GRAY = RGBColor(0x66, 0x66, 0x66)

SLIDE_W = Inches(13.333)
SLIDE_H = Inches(7.5)

prs = Presentation()
prs.slide_width = SLIDE_W
prs.slide_height = SLIDE_H

BLANK_LAYOUT = prs.slide_layouts[6]  # Blank


def add_bg(slide, color=WHITE):
    """Set solid background color."""
    bg = slide.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = color


def add_shape(slide, left, top, width, height, fill_color, line_color=None):
    """Add a rectangle shape."""
    shape = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, left, top, width, height)
    shape.fill.solid()
    shape.fill.fore_color.rgb = fill_color
    if line_color:
        shape.line.color.rgb = line_color
    else:
        shape.line.fill.background()
    return shape


def add_text_box(slide, left, top, width, height, text, font_size=18,
                 color=DARK_GRAY, bold=False, alignment=PP_ALIGN.LEFT,
                 font_name="Calibri"):
    """Add a text box with formatted text."""
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = text
    p.font.size = Pt(font_size)
    p.font.color.rgb = color
    p.font.bold = bold
    p.font.name = font_name
    p.alignment = alignment
    return txBox


def add_speaker_notes(slide, text):
    """Add speaker notes to a slide."""
    notes_slide = slide.notes_slide
    notes_slide.notes_text_frame.text = text


def add_bullet_slide(slide, items, left, top, width, height,
                     font_size=16, color=DARK_GRAY, spacing=Pt(8)):
    """Add bulleted text to a slide."""
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = True

    for i, item in enumerate(items):
        if i == 0:
            p = tf.paragraphs[0]
        else:
            p = tf.add_paragraph()
        p.text = item
        p.font.size = Pt(font_size)
        p.font.color.rgb = color
        p.font.name = "Calibri"
        p.space_after = spacing
        p.level = 0
    return txBox


# ============================================================
# SLIDE 1: Title
# ============================================================
slide = prs.slides.add_slide(BLANK_LAYOUT)
add_bg(slide, NAVY)

# Accent bar
add_shape(slide, Inches(0), Inches(3.2), Inches(13.333), Inches(0.06), TEAL)

add_text_box(slide, Inches(1), Inches(1.5), Inches(11), Inches(1.5),
             "Comparative Diagnostic Accuracy of\nMachine Learning Models for Breast Cancer Classification",
             font_size=32, color=WHITE, bold=True, alignment=PP_ALIGN.LEFT)

add_text_box(slide, Inches(1), Inches(3.6), Inches(11), Inches(0.5),
             "Using Fine Needle Aspiration Cytology Features",
             font_size=20, color=RGBColor(0xAA, 0xCC, 0xEE), bold=False)

add_text_box(slide, Inches(1), Inches(5.0), Inches(11), Inches(0.8),
             "MedSci Skills Demo  |  Wisconsin Breast Cancer Dataset  |  2026",
             font_size=14, color=RGBColor(0x88, 0xAA, 0xCC))

add_text_box(slide, Inches(1), Inches(5.8), Inches(11), Inches(0.5),
             "Generated by: analyze-stats + make-figures + write-paper + check-reporting + present-paper",
             font_size=12, color=RGBColor(0x66, 0x88, 0xAA))

add_speaker_notes(slide,
    "Welcome. This presentation demonstrates the MedSci Skills pipeline — "
    "from a single line of Python code to a publication-ready manuscript, figures, "
    "reporting compliance audit, and now this presentation. "
    "All generated using open-source skills for Claude Code.")


# ============================================================
# SLIDE 2: Background
# ============================================================
slide = prs.slides.add_slide(BLANK_LAYOUT)
add_bg(slide, WHITE)
add_shape(slide, Inches(0), Inches(0), Inches(13.333), Inches(1.1), NAVY)
add_text_box(slide, Inches(0.8), Inches(0.2), Inches(11), Inches(0.7),
             "Background", font_size=28, color=WHITE, bold=True)

items = [
    "Breast cancer: most common malignancy in women (2.3M new cases/year globally)",
    "Fine needle aspiration (FNA) cytology: minimally invasive, first-line diagnostic tool",
    "Wisconsin BC Dataset: 569 FNA specimens, 30 nuclear morphometric features",
    "30,000+ citations since Wolberg et al. (1995) — the benchmark for ML in pathology",
    "Gap: head-to-head ML model comparisons with proper statistical testing are uncommon",
]
add_bullet_slide(slide, items, Inches(0.8), Inches(1.5), Inches(11.5), Inches(5.0),
                 font_size=18)

add_speaker_notes(slide,
    "Breast cancer remains the most frequently diagnosed cancer in women worldwide. "
    "FNA cytology is a key diagnostic tool for palpable breast masses. "
    "The Wisconsin dataset is one of the most cited in machine learning — "
    "30 features from digitized FNA images. "
    "Despite thousands of studies, rigorous head-to-head comparisons with "
    "DeLong testing for AUC differences are surprisingly rare.")


# ============================================================
# SLIDE 3: Objectives
# ============================================================
slide = prs.slides.add_slide(BLANK_LAYOUT)
add_bg(slide, WHITE)
add_shape(slide, Inches(0), Inches(0), Inches(13.333), Inches(1.1), NAVY)
add_text_box(slide, Inches(0.8), Inches(0.2), Inches(11), Inches(0.7),
             "Study Objectives", font_size=28, color=WHITE, bold=True)

add_text_box(slide, Inches(0.8), Inches(1.8), Inches(11.5), Inches(0.6),
             "Primary Objective", font_size=20, color=TEAL, bold=True)
add_text_box(slide, Inches(0.8), Inches(2.4), Inches(11.5), Inches(1.0),
             "Compare diagnostic accuracy (AUC) of three ML classifiers for breast FNA classification",
             font_size=18, color=DARK_GRAY)

add_text_box(slide, Inches(0.8), Inches(3.6), Inches(11.5), Inches(0.6),
             "Models Compared", font_size=20, color=TEAL, bold=True)
items = [
    "1.  Logistic Regression (L2 regularization)",
    "2.  Random Forest (100 trees)",
    "3.  Support Vector Machine (RBF kernel + Platt scaling)",
]
add_bullet_slide(slide, items, Inches(0.8), Inches(4.2), Inches(11.5), Inches(2.5),
                 font_size=18)

add_speaker_notes(slide,
    "Our primary objective was to compare three widely used classifiers: "
    "logistic regression, random forest, and SVM. "
    "We chose these because they represent three fundamentally different approaches: "
    "linear, ensemble, and kernel-based. "
    "All used default hyperparameters to ensure a fair, reproducible comparison.")


# ============================================================
# SLIDE 4: Methods — Study Design
# ============================================================
slide = prs.slides.add_slide(BLANK_LAYOUT)
add_bg(slide, WHITE)
add_shape(slide, Inches(0), Inches(0), Inches(13.333), Inches(1.1), NAVY)
add_text_box(slide, Inches(0.8), Inches(0.2), Inches(11), Inches(0.7),
             "Methods", font_size=28, color=WHITE, bold=True)

# Left column
add_text_box(slide, Inches(0.8), Inches(1.5), Inches(5.5), Inches(0.5),
             "Study Design", font_size=18, color=TEAL, bold=True)
items_left = [
    "Retrospective cross-sectional diagnostic accuracy study",
    "Dataset: Wisconsin BC (UCI / sklearn)",
    "n = 569 (357 benign, 212 malignant)",
    "Reference standard: histopathological diagnosis",
    "Reporting guideline: STARD 2015",
]
add_bullet_slide(slide, items_left, Inches(0.8), Inches(2.1), Inches(5.5), Inches(4.0),
                 font_size=15)

# Right column
add_text_box(slide, Inches(7.0), Inches(1.5), Inches(5.5), Inches(0.5),
             "Evaluation Strategy", font_size=18, color=TEAL, bold=True)
items_right = [
    "Stratified 5-fold cross-validation (seed = 42)",
    "StandardScaler fit on training fold only (no leakage)",
    "Primary endpoint: AUC with DeLong 95% CI",
    "Secondary: Sensitivity, Specificity, PPV, NPV (Wilson CI)",
    "Pairwise comparison: DeLong test",
]
add_bullet_slide(slide, items_right, Inches(7.0), Inches(2.1), Inches(5.5), Inches(4.0),
                 font_size=15)

add_speaker_notes(slide,
    "This was a retrospective diagnostic accuracy study. "
    "Key methodological points: stratified 5-fold CV to maintain class proportions, "
    "StandardScaler fitted exclusively on training data within each fold to prevent leakage, "
    "and DeLong method for AUC confidence intervals — "
    "which is the correct approach for correlated ROC curves on the same dataset.")


# ============================================================
# SLIDE 5: Table 1 — Demographics
# ============================================================
slide = prs.slides.add_slide(BLANK_LAYOUT)
add_bg(slide, WHITE)
add_shape(slide, Inches(0), Inches(0), Inches(13.333), Inches(1.1), NAVY)
add_text_box(slide, Inches(0.8), Inches(0.2), Inches(11), Inches(0.7),
             "Results — Table 1: Baseline Characteristics", font_size=28, color=WHITE, bold=True)

# Table header
headers = ["Variable", "Benign (n=357)", "Malignant (n=212)", "p-value"]
col_widths = [Inches(3.5), Inches(3.0), Inches(3.0), Inches(1.5)]
table_left = Inches(1.2)
table_top = Inches(1.5)
table_height = Inches(5.0)

rows_data = [
    ["Age (years), mean +/- SD", "53.8 +/- 11.9", "55.1 +/- 10.6", "0.219"],
    ["Mean radius, median (IQR)", "12.2 (11.1-13.4)", "17.3 (15.1-19.6)", "<0.001"],
    ["Mean texture, mean +/- SD", "17.9 +/- 4.0", "21.6 +/- 3.8", "<0.001"],
    ["Mean perimeter, median (IQR)", "78.2 (70.9-86.1)", "114.2 (98.7-129.9)", "<0.001"],
    ["Mean area, median (IQR)", "458.4 (378.2-551.1)", "932.0 (705.3-1203.8)", "<0.001"],
    ["Mean smoothness, mean +/- SD", "0.09 +/- 0.01", "0.10 +/- 0.01", "<0.001"],
]

n_rows = len(rows_data) + 1
n_cols = len(headers)
total_w = sum(w for w in col_widths)
table = slide.shapes.add_table(n_rows, n_cols, table_left, table_top,
                                total_w, Inches(0.4 * n_rows)).table

# Set column widths
for i, w in enumerate(col_widths):
    table.columns[i].width = w

# Header row
for j, h in enumerate(headers):
    cell = table.cell(0, j)
    cell.text = h
    for paragraph in cell.text_frame.paragraphs:
        paragraph.font.size = Pt(13)
        paragraph.font.bold = True
        paragraph.font.color.rgb = WHITE
        paragraph.font.name = "Calibri"
    cell.fill.solid()
    cell.fill.fore_color.rgb = NAVY

# Data rows
for i, row in enumerate(rows_data):
    for j, val in enumerate(row):
        cell = table.cell(i + 1, j)
        cell.text = val
        for paragraph in cell.text_frame.paragraphs:
            paragraph.font.size = Pt(12)
            paragraph.font.color.rgb = DARK_GRAY
            paragraph.font.name = "Calibri"
            if j == 3 and val == "<0.001":
                paragraph.font.bold = True
                paragraph.font.color.rgb = ORANGE
        cell.fill.solid()
        cell.fill.fore_color.rgb = LIGHT_GRAY if i % 2 == 0 else WHITE

add_text_box(slide, Inches(1.2), Inches(6.2), Inches(10), Inches(0.5),
             "All morphometric features significantly different between groups (p < 0.001) except age",
             font_size=13, color=MED_GRAY)

add_speaker_notes(slide,
    "Table 1 shows baseline characteristics. Age was comparable between groups. "
    "All morphometric features — radius, texture, perimeter, area, smoothness — "
    "were significantly different, with malignant specimens showing larger values. "
    "This is expected and confirms the discriminative potential of these features.")


# ============================================================
# SLIDE 6: ROC Curves (image)
# ============================================================
slide = prs.slides.add_slide(BLANK_LAYOUT)
add_bg(slide, WHITE)
add_shape(slide, Inches(0), Inches(0), Inches(13.333), Inches(1.1), NAVY)
add_text_box(slide, Inches(0.8), Inches(0.2), Inches(11), Inches(0.7),
             "Results — ROC Curves", font_size=28, color=WHITE, bold=True)

# Insert ROC curve image
roc_path = os.path.join(os.path.dirname(__file__), "figures", "roc_curve.png")
if os.path.exists(roc_path):
    slide.shapes.add_picture(roc_path, Inches(3.5), Inches(1.3), Inches(6.0), Inches(6.0))

# Key finding callout
callout = add_shape(slide, Inches(0.5), Inches(2.0), Inches(2.8), Inches(3.5), LIGHT_GRAY)
add_text_box(slide, Inches(0.6), Inches(2.1), Inches(2.6), Inches(0.5),
             "Key Finding", font_size=14, color=TEAL, bold=True)
add_text_box(slide, Inches(0.6), Inches(2.6), Inches(2.6), Inches(2.8),
             "All three models achieved\nAUC > 0.987\n\nLogistic Regression\nand SVM were\nnot significantly\ndifferent (p = 0.568)",
             font_size=13, color=DARK_GRAY)

add_speaker_notes(slide,
    "The ROC curves show all three models clustered near the upper left corner, "
    "indicating excellent discrimination. The legend shows AUC with DeLong 95% CIs. "
    "Visually the curves are nearly overlapping, but formal statistical testing "
    "reveals important differences we'll discuss on the next slide.")


# ============================================================
# SLIDE 7: Performance Table
# ============================================================
slide = prs.slides.add_slide(BLANK_LAYOUT)
add_bg(slide, WHITE)
add_shape(slide, Inches(0), Inches(0), Inches(13.333), Inches(1.1), NAVY)
add_text_box(slide, Inches(0.8), Inches(0.2), Inches(11), Inches(0.7),
             "Results — Diagnostic Performance (5-Fold CV)", font_size=28, color=WHITE, bold=True)

headers2 = ["Model", "AUC (95% CI)", "Sensitivity", "Specificity", "PPV", "NPV", "Accuracy"]
col_w2 = [Inches(2.2), Inches(2.5), Inches(1.7), Inches(1.7), Inches(1.7), Inches(1.7), Inches(1.7)]
perf_data = [
    ["Logistic Regression", "0.995\n(0.990-1.000)", "0.943\n(0.904-0.967)", "0.992\n(0.976-0.997)",
     "0.987\n(0.965-0.996)", "0.967\n(0.944-0.981)", "0.974\n(0.957-0.984)"],
    ["Random Forest", "0.987\n(0.976-0.998)", "0.934\n(0.892-0.960)", "0.966\n(0.942-0.981)",
     "0.943\n(0.902-0.967)", "0.961\n(0.937-0.977)", "0.954\n(0.934-0.969)"],
    ["SVM (RBF)", "0.994\n(0.989-0.999)", "0.958\n(0.921-0.978)", "0.989\n(0.972-0.996)",
     "0.981\n(0.952-0.994)", "0.975\n(0.955-0.988)", "0.977\n(0.961-0.987)"],
]

table2 = slide.shapes.add_table(4, 7, Inches(0.3), Inches(1.5),
                                 sum(col_w2), Inches(3.6)).table
for i, w in enumerate(col_w2):
    table2.columns[i].width = w

for j, h in enumerate(headers2):
    cell = table2.cell(0, j)
    cell.text = h
    cell.vertical_anchor = MSO_ANCHOR.MIDDLE
    for p in cell.text_frame.paragraphs:
        p.font.size = Pt(11)
        p.font.bold = True
        p.font.color.rgb = WHITE
        p.font.name = "Calibri"
        p.alignment = PP_ALIGN.CENTER
    cell.fill.solid()
    cell.fill.fore_color.rgb = NAVY

for i, row in enumerate(perf_data):
    for j, val in enumerate(row):
        cell = table2.cell(i + 1, j)
        cell.text = val
        cell.vertical_anchor = MSO_ANCHOR.MIDDLE
        for p in cell.text_frame.paragraphs:
            p.font.size = Pt(11)
            p.font.color.rgb = DARK_GRAY
            p.font.name = "Calibri"
            p.alignment = PP_ALIGN.CENTER if j > 0 else PP_ALIGN.LEFT
        # Highlight best AUC row
        if i == 0:  # LR row
            cell.fill.solid()
            cell.fill.fore_color.rgb = RGBColor(0xE8, 0xF4, 0xFD)
        else:
            cell.fill.solid()
            cell.fill.fore_color.rgb = WHITE if i % 2 == 1 else LIGHT_GRAY

# DeLong comparison box
add_shape(slide, Inches(0.5), Inches(5.4), Inches(12.3), Inches(1.5), RGBColor(0xFE, 0xF3, 0xE6))
add_text_box(slide, Inches(0.7), Inches(5.5), Inches(12), Inches(0.4),
             "DeLong Pairwise AUC Comparison", font_size=14, color=ORANGE, bold=True)
add_text_box(slide, Inches(0.7), Inches(5.95), Inches(12), Inches(0.8),
             "LR vs RF: z = 1.964, p = 0.050  |  LR vs SVM: z = 0.570, p = 0.568  |  RF vs SVM: z = -2.028, p = 0.043*",
             font_size=13, color=DARK_GRAY)

add_speaker_notes(slide,
    "All three models performed excellently. Logistic regression achieved the highest AUC "
    "at 0.995, closely followed by SVM at 0.994. "
    "The DeLong test shows SVM significantly outperformed random forest (p=0.043), "
    "while LR and SVM were statistically indistinguishable (p=0.568). "
    "Note that all metrics include 95% CIs — this is a requirement for proper reporting "
    "per STARD guidelines.")


# ============================================================
# SLIDE 8: Discussion — Key Findings
# ============================================================
slide = prs.slides.add_slide(BLANK_LAYOUT)
add_bg(slide, WHITE)
add_shape(slide, Inches(0), Inches(0), Inches(13.333), Inches(1.1), NAVY)
add_text_box(slide, Inches(0.8), Inches(0.2), Inches(11), Inches(0.7),
             "Discussion", font_size=28, color=WHITE, bold=True)

items_disc = [
    "Simpler models (LR) matched complex ones (SVM) — interpretability advantage",
    "RF significantly inferior to SVM despite AUC > 0.98 — DeLong test matters",
    "Point estimates alone would have missed this difference",
    "Consistent with Wolberg & Mangasarian (1990): 97.5% accuracy with linear methods",
]
add_text_box(slide, Inches(0.8), Inches(1.5), Inches(5.5), Inches(0.5),
             "Key Takeaways", font_size=20, color=TEAL, bold=True)
add_bullet_slide(slide, items_disc, Inches(0.8), Inches(2.1), Inches(5.5), Inches(4.0),
                 font_size=16)

items_lim = [
    "Curated benchmark, not prospective clinical cohort",
    "Pre-computed features — abstracts away real-world image variability",
    "Synthetic age variable (for demo purposes)",
    "No hyperparameter tuning performed",
]
add_text_box(slide, Inches(7.0), Inches(1.5), Inches(5.5), Inches(0.5),
             "Limitations", font_size=20, color=ORANGE, bold=True)
add_bullet_slide(slide, items_lim, Inches(7.0), Inches(2.1), Inches(5.5), Inches(4.0),
                 font_size=16)

add_speaker_notes(slide,
    "Two key discussion points. First, logistic regression matched SVM — "
    "suggesting that for well-characterized feature spaces, simpler is often better. "
    "Second, the DeLong test detected a significant difference between RF and SVM "
    "that point estimates would have missed. This underscores why we need proper "
    "statistical comparison, not just eyeballing AUC numbers. "
    "Limitations include the curated nature of the dataset and lack of hyperparameter optimization.")


# ============================================================
# SLIDE 9: STARD Compliance
# ============================================================
slide = prs.slides.add_slide(BLANK_LAYOUT)
add_bg(slide, WHITE)
add_shape(slide, Inches(0), Inches(0), Inches(13.333), Inches(1.1), NAVY)
add_text_box(slide, Inches(0.8), Inches(0.2), Inches(11), Inches(0.7),
             "STARD 2015 Compliance Audit", font_size=28, color=WHITE, bold=True)

# Compliance summary boxes
for i, (label, count, pct, color) in enumerate([
    ("PRESENT", "19", "63%", GREEN),
    ("PARTIAL", "5", "17%", ORANGE),
    ("MISSING", "6", "20%", RGBColor(0xCC, 0x33, 0x33)),
]):
    x = Inches(1.0 + i * 3.8)
    box = add_shape(slide, x, Inches(1.5), Inches(3.2), Inches(2.0), LIGHT_GRAY)
    add_text_box(slide, x + Inches(0.2), Inches(1.6), Inches(2.8), Inches(0.5),
                 label, font_size=16, color=color, bold=True, alignment=PP_ALIGN.CENTER)
    add_text_box(slide, x + Inches(0.2), Inches(2.1), Inches(2.8), Inches(0.8),
                 count, font_size=48, color=color, bold=True, alignment=PP_ALIGN.CENTER)
    add_text_box(slide, x + Inches(0.2), Inches(2.9), Inches(2.8), Inches(0.4),
                 f"of 30 items ({pct})", font_size=12, color=MED_GRAY, alignment=PP_ALIGN.CENTER)

# Missing items detail
add_text_box(slide, Inches(0.8), Inches(4.0), Inches(11.5), Inches(0.5),
             "Auto-detected Missing Items with Fix Recommendations:", font_size=16, color=DARK_GRAY, bold=True)
missing_items = [
    "Item 7 (Sampling): Add convenience series statement",
    "Item 11 (Blinding): Add CV-based blinding explanation",
    "Item 13 (Sample size): Add justification or state full dataset used",
    "Items 20/22 (Indeterminate): State no indeterminate results observed",
    "Item 28 (Funding): Add funding disclosure",
]
add_bullet_slide(slide, missing_items, Inches(0.8), Inches(4.5), Inches(11.5), Inches(2.5),
                 font_size=14)

add_speaker_notes(slide,
    "The check-reporting skill automatically audited the manuscript against STARD 2015. "
    "19 of 30 items were fully present, 5 partial, 6 missing. "
    "Critically, it provides specific fix recommendations — "
    "for example, telling us exactly what sentence to add for Item 7 (sampling method). "
    "This is what usually takes a reviewer 30+ minutes, done in seconds.")


# ============================================================
# SLIDE 10: Pipeline Summary
# ============================================================
slide = prs.slides.add_slide(BLANK_LAYOUT)
add_bg(slide, WHITE)
add_shape(slide, Inches(0), Inches(0), Inches(13.333), Inches(1.1), NAVY)
add_text_box(slide, Inches(0.8), Inches(0.2), Inches(11), Inches(0.7),
             "MedSci Skills Pipeline — What Was Generated", font_size=28, color=WHITE, bold=True)

# Pipeline steps
steps = [
    ("1", "Data Loading", "sklearn one-liner\n569 samples", TEAL),
    ("2", "analyze-stats", "Table 1 + 3-model\nDeLong comparison", TEAL),
    ("3", "make-figures", "ROC curve\n300 dpi + PDF", GREEN),
    ("4", "write-paper", "IMRAD manuscript\n~1,600 words", ORANGE),
    ("5", "check-reporting", "STARD 30-item\ncompliance audit", RGBColor(0xCC, 0x33, 0x33)),
    ("6", "present-paper", "This presentation\n12 slides + notes", NAVY),
]

for i, (num, title, desc, color) in enumerate(steps):
    x = Inches(0.5 + i * 2.1)
    y = Inches(1.8)

    # Circle with number
    circle = slide.shapes.add_shape(MSO_SHAPE.OVAL, x + Inches(0.6), y, Inches(0.7), Inches(0.7))
    circle.fill.solid()
    circle.fill.fore_color.rgb = color
    circle.line.fill.background()
    tf = circle.text_frame
    tf.paragraphs[0].text = num
    tf.paragraphs[0].font.size = Pt(20)
    tf.paragraphs[0].font.color.rgb = WHITE
    tf.paragraphs[0].font.bold = True
    tf.paragraphs[0].alignment = PP_ALIGN.CENTER

    # Arrow (except last)
    if i < len(steps) - 1:
        add_text_box(slide, x + Inches(1.4), y + Inches(0.1), Inches(0.6), Inches(0.5),
                     "-->", font_size=16, color=MED_GRAY, alignment=PP_ALIGN.CENTER)

    # Title + description
    add_text_box(slide, x, y + Inches(0.9), Inches(1.9), Inches(0.5),
                 title, font_size=14, color=color, bold=True, alignment=PP_ALIGN.CENTER)
    add_text_box(slide, x, y + Inches(1.4), Inches(1.9), Inches(1.0),
                 desc, font_size=11, color=MED_GRAY, alignment=PP_ALIGN.CENTER)

# Bottom summary
add_shape(slide, Inches(0.5), Inches(5.0), Inches(12.3), Inches(1.8), RGBColor(0xF0, 0xF7, 0xFE))
add_text_box(slide, Inches(0.8), Inches(5.1), Inches(11.7), Inches(0.5),
             "Total Output: 14 files  |  2 Python scripts  |  0 hallucinated citations",
             font_size=16, color=NAVY, bold=True, alignment=PP_ALIGN.CENTER)
add_text_box(slide, Inches(0.8), Inches(5.7), Inches(11.7), Inches(0.8),
             "Every CI calculated correctly (DeLong for AUC, Wilson for proportions)  |  "
             "Cross-validation prevents data leakage  |  STARD audit catches 6 gaps automatically  |  "
             "All code reproducible (seed = 42)",
             font_size=12, color=MED_GRAY, alignment=PP_ALIGN.CENTER)

add_speaker_notes(slide,
    "This slide summarizes the full pipeline. Six skills were used in sequence: "
    "data loading, statistical analysis, figure generation, manuscript writing, "
    "STARD compliance checking, and presentation creation. "
    "14 output files from 2 Python scripts and a series of skill invocations. "
    "Zero hallucinated citations — every reference needs verified DOI or PMID.")


# ============================================================
# SLIDE 11: Conclusion
# ============================================================
slide = prs.slides.add_slide(BLANK_LAYOUT)
add_bg(slide, WHITE)
add_shape(slide, Inches(0), Inches(0), Inches(13.333), Inches(1.1), NAVY)
add_text_box(slide, Inches(0.8), Inches(0.2), Inches(11), Inches(0.7),
             "Conclusions", font_size=28, color=WHITE, bold=True)

conclusions = [
    "LR and SVM achieved near-perfect diagnostic accuracy (AUC > 0.99)",
    "SVM significantly outperformed RF (DeLong p = 0.043)",
    "Simpler models (LR) may be preferred for clinical deployment — comparable accuracy, greater interpretability",
    "Formal statistical comparison (DeLong test) is essential — point estimates are insufficient",
]
add_bullet_slide(slide, conclusions, Inches(0.8), Inches(1.5), Inches(11.5), Inches(3.0),
                 font_size=18, spacing=Pt(16))

add_shape(slide, Inches(0.5), Inches(5.0), Inches(12.3), Inches(1.8), RGBColor(0xF0, 0xF7, 0xFE))
add_text_box(slide, Inches(0.8), Inches(5.2), Inches(11.7), Inches(1.2),
             "This entire presentation — from data loading to slides — was generated\n"
             "using MedSci Skills, an open-source bundle of 20 Claude Code skills\n"
             "for medical researchers.\n\n"
             "github.com/Aperivue/medsci-skills",
             font_size=14, color=NAVY, alignment=PP_ALIGN.CENTER)

add_speaker_notes(slide,
    "In conclusion, logistic regression and SVM both achieved AUC above 0.99. "
    "The key message is twofold: first, simpler models can match complex ones "
    "when features are well-characterized. Second, the DeLong test is essential "
    "for proper model comparison. "
    "And the meta-message: this entire presentation was auto-generated by MedSci Skills.")


# ============================================================
# SLIDE 12: Thank You / CTA
# ============================================================
slide = prs.slides.add_slide(BLANK_LAYOUT)
add_bg(slide, NAVY)
add_shape(slide, Inches(0), Inches(3.2), Inches(13.333), Inches(0.06), TEAL)

add_text_box(slide, Inches(1), Inches(2.0), Inches(11), Inches(1.0),
             "Thank You", font_size=40, color=WHITE, bold=True, alignment=PP_ALIGN.CENTER)

add_text_box(slide, Inches(1), Inches(3.6), Inches(11), Inches(1.0),
             "20 skills  |  MIT licensed  |  Free forever",
             font_size=20, color=RGBColor(0xAA, 0xCC, 0xEE), alignment=PP_ALIGN.CENTER)

add_text_box(slide, Inches(1), Inches(4.8), Inches(11), Inches(0.5),
             "github.com/Aperivue/medsci-skills",
             font_size=18, color=TEAL, alignment=PP_ALIGN.CENTER)

add_text_box(slide, Inches(1), Inches(5.6), Inches(11), Inches(0.5),
             "Built by a radiologist who writes papers — not a tech company that doesn't.",
             font_size=14, color=RGBColor(0x88, 0xAA, 0xCC), alignment=PP_ALIGN.CENTER)

add_speaker_notes(slide,
    "Thank you for your attention. MedSci Skills is open source, MIT licensed, "
    "and free forever. It was built by a radiologist who actually writes papers, "
    "so it knows what proper statistical reporting looks like. "
    "Questions?")


# ============================================================
# SAVE
# ============================================================
output_path = "output/presentation.pptx"
prs.save(output_path)
print(f"Saved: {output_path}")
print(f"Slides: {len(prs.slides)}")
print("Done.")
